UPDATE JAVA_FREEBOARD
SET WRITER = NULL;

SELECT 
    'private '||
   DECODE( DATA_TYPE , 'NUMBER', 'int ', 'String ' )||
    LOWER(COLUMN_NAME)||';'
FROM COLS
WHERE TABLE_NAME = 'JAVA_FREEBOARD'
ORDER BY COLUMN_ID;

SELECT F.*, M.NAME writer
FROM JAVA_FREEBOARD F, JAVA_MEMBER M
WHERE F.MEM_NO = M.MEM_NO 
AND F.DELYN = 'N'
AND BAN = 'N';

-- 날짜 to_char로 변환
SELECT NO, F.NAME, CONTENT, TO_CHAR(REGDATE, 'YYYY.MM.DD') REGDATE, F.MEM_NO, M.NAME WRITER
FROM JAVA_FREEBOARD F, JAVA_MEMBER M
WHERE F.MEM_NO = M.MEM_NO 
AND F.DELYN = 'N'
AND BAN = 'N';

-- freeDetail
SELECT * FROM 
(SELECT NO, F.NAME, CONTENT, TO_CHAR(REGDATE, 'YYYY.MM.DD') REGDATE, F.MEM_NO, M.NAME WRITER,
       LAG(NO) OVER(ORDER BY NO) PREVNO,    -- LAG : 이전 번호 가져옴
       LEAD(NO) OVER(ORDER BY NO) NEXTNO    -- LEAD : 다음 번호 가져옴
FROM JAVA_FREEBOARD F, JAVA_MEMBER M
WHERE F.MEM_NO = M.MEM_NO 
AND F.DELYN = 'N'
AND BAN = 'N')
WHERE NO = 2;

-- 
SELECT 
    'private '||
   DECODE( DATA_TYPE , 'NUMBER', 'int ', 'String ' )||
    LOWER(COLUMN_NAME)||';'
FROM COLS
WHERE TABLE_NAME = 'JAVA_MEMBER'
ORDER BY COLUMN_ID;

-- freeUpdate
UPDATE JAVA_FREEBOARD
SET CONTENT = 'TEST'
WHERE NO = 2;

-- like  검색
SELECT *
FROM JAVA_MENU
WHERE CONTENT LIKE '%'||?||'%';
--WHERE CONTENT LIKE '%'||치킨||'%'
