INSERT INTO BOOK_HOLD
SELECT ROWNUM+5, BOOK_NO FROM BOOK;

-- bookList
SELECT BOOK_NO, TITLE, CONTENT, TO_CHAR(PUBDATE, 'YYYY.MM.DD')PUBDATE FROM BOOK;

-- 고유번호 출력
SELECT *
FROM 
    (SELECT ROWNUM RN , B.*, H.HOLD_NO
     FROM BOOK B, BOOK_HOLD H
     WHERE B.BOOK_NO = H.BOOK_NO
     ORDER BY B.BOOK_NO)
WHERE (RN >= 6 AND RN <= 10);